routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@home')->name('home');

Route::resource('photos', 'PhotoController');

app/Cindoc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cindoc extends Model
{
    protected $table = 'cindoc';

    public function photo() {
        return $this->belongsTo(__NAMESPACE__ . '\Photo');
    }
}

app/Date.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Date extends Model
{
    protected $table = 'date';

    public function photo() {
        return $this->belongsTo(__NAMESPACE__ . "\\Photo", "date_id");
    }
}

app/Description.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Description extends Model
{
    protected $table = 'description';

    public function photos() {
        return $this->belongsTo(__NAMESPACE__ . "\\Photo", "description_id");
    }
}

app/Geo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Geo extends Model
{
    protected $table = 'geo';

    public function photos() {
        return $this->belongsTo(__NAMESPACE__ . "\\Photo", "geo_id");
    }
}

app/Iconographie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Iconographie extends Model
{
    protected $table = 'iconographie';

    public function iconographies() {
        return $this->hasMany(__NAMESPACE__ . '\Iconographies');
    }
}

app/Iconographies.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Iconographies extends Model
{
    protected $table = 'iconographies';

    public function photo() {
        return $this->belongsTo(__NAMESPACE__ . '\Photo');
    }
}

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $table = 'photo';

    public function cindocs() {
        return $this->hasMany(__NAMESPACE__ . "\\Cindoc", "photo_id");
    }

    public function date()
    {
        return $this->hasOne(__NAMESPACE__ . "\\Date", 'id');
    }

    public function geo() {
        return $this->hasOne(__NAMESPACE__ . "\\Geo", "id");
    }

    public function description() {
        return $this->hasOne(__NAMESPACE__ . "\\Description", "id");
    }

    public function tailles() {
        return $this->belongsToMany(__NAMESPACE__ . "\\Taille", "tailles");
    }
}

app/Sujet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sujet extends Model
{
    //
}

app/Sujets.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sujets extends Model
{
    //
}

app/Taille.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Taille extends Model
{
    protected $table = 'taille';

    public function photos() {
        return $this->belongsToMany(__NAMESPACE__ . "\\Photo", "tailles");
    }
}

app/Tailles.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tailles extends Model
{
    protected $table = 'tailles';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

class DashboardController extends Controller {

    public function home() {
        return view('dashboard/home');
    }

}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use App\Photo;
use Illuminate\Http\Request;

class PhotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $photos = Photo::take(100)->get();
        return view('photos.index', compact('photos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('photos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function show(Photo $photo)
    {
        return view('photos.show', compact('photo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function edit(Photo $photo)
    {
        return view('photos.edit', compact('photo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Photo $photo)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Photo $photo)
    {
        //
    }
}

resources/views/dashboard/home.blade.php
@extends('default')

@section('content')
    <h3>Lorem ipsum</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
@endsection

resources/views/default.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="./css/style.css" rel="stylesheet">

</head>

<body style="padding-top:50px">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('home') . '/' }}">Home</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                <li><a href="{{ route('photos.index') }}">Photos</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="starter-template" style="padding-top:40px;">
        @yield('content')
    </div>
</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.min.js"></script>

@yield('script')

</body>
</html>

resources/views/photos/create.blade.php
@extends('default')

@section('content')

@endsection

resources/views/photos/edit.blade.php
@extends('default')

@section('content')

@endsection

resources/views/photos/index.blade.php
@extends('default')

@section('content')
    <div>
        <a href="{{ route('photos.create') }}" class="btn btn-primary">Créer une nouvelle photo</a>
    </div>
    <table class="table">
        <tr>
            <th>Réf(s) cindoc</th>
            <th>Série</th>
            <th>Article</th>
            <th>Ville</th>
            <th>Taille</th>
            <th colspan="3">Actions</th>
        </tr>
    @foreach($photos as $photo)
            <tr>
                <td>
                    @foreach($photo->cindocs as $cindoc)
                       {{ $cindoc->label }}
                    @endforeach
                </td>
                <td>{{ $photo->serie }}</td>
                <td>{{ $photo->article}}</td>
                <td>{{ $photo->geo->commune }}</td>
                <td>{{ $photo->taille}}</td>
                <td><a class="btn btn-default" href="{{ route('photos.show', $photo)}}">Voir</a></td>
                <td><a class="btn btn-primary" href="{{ route('photos.edit', $photo)}}">Editer</a></td>
                <td><a class="btn btn-danger" href="{{ route('photos.destroy', $photo)}}">Supprimer</a></td>
            </tr>
        @endforeach
    </table>
@endsection

resources/views/photos/show.blade.php
@extends('default')

@section('content')
    <dl>
        <dt>Serie</dd>
        <dd>{{ $photo->serie }}</dd>
        <dt>Article</dd>
        <dd>{{ $photo->article }}</dd>
        <dt>Discriminant</dd>
        <dd>{{ $photo->discriminant }}</dd>
        <dt>Notes</dd>
        <dd>{{ $photo->notes }}</dd>
        <dt>Index personnes</dd>
        <dd>{{ $photo->index_personnes }}</dd>
        <dt>Fichier numérique</dd>
        <dd>{{ $photo->fichier_num }}</dd>
        <dt>Nombre de cliché(s)</dd>
        <dd>{{ $photo->nb_cliche }}</dd>
        <dt>Support</dd>
        <dd>{{ $photo->support }}</dd>
        <dt>Chroma</dd>
        <dd>{{ $photo->chroma }}</dd>
        <dt>Remarques</dd>
        <dd>{{ $photo->remarques }}</dd>
        @if($photo->date)
            <dt>Date (jj/mm/aaaa)</dd>
            <dd>
                {{ $photo->date->jour }}/{{ $photo->date->mois }}/{{ $photo->date->annee }}
            </dd>
        @endif
        @if($photo->geo)
            <dt>Geo</dd>
            <dd>{{ $photo->geo->commune }}</dd>
        @endif
        @if($photo->date)
            <dt>Description</dd>
            <dd>{{ $photo->description->label }}</dd>
        @endif
        <dt>Taille(s)</dt>
        <dd>
            @foreach($photo->tailles as $taille)
                {{ $taille->largeur }} x {{ $taille->largeur }} cm
            @endforeach
        </dd>
        <dt>Sujet(s)</dt>
        <dd>
            @foreach($photo->sujets as $sujet)
                {{ $sujet->sujet }}
            @endforeach
        </dd>
        <dt>Index iconographique)</dt>
        <dd>
            @foreach($photo->iconographies as $icono)
                {{ $icono->label }}
            @endforeach
        </dd>
    </dl>
    <div id="map" style="height:420px"></div>
    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 47.916672, lng: 1.9},
                zoom: 8
            });
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC07ggQxm2RGneiEAoEhrolExEaaJp6dyc&callback=initMap"
            async defer></script>
@endsection